#+TITLE: A. Exercises
#+AUTHOR: David Wakeham
#+OPTIONS: toc:nil num:nil ^:nil H:4
#+HTML_DOCTYPE: html5
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="enhanced_tufte.css">
#+HTML_HEAD: <script src="contents.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="sidebar_darkmode.js"></script>
#+HTML_HEAD: <style>.smallcaps{font-variant:small-caps;letter-spacing:.04em}</style>
#+HTML_HEAD: <style>
#+HTML_HEAD:   /* (a), (b) at the top level; i., ii. one level down */
#+HTML_HEAD:   #content ol { list-style-type: lower-alpha; }
#+HTML_HEAD:   #content ol ol { list-style-type: lower-roman; }
#+HTML_HEAD:   #content ol li { margin-bottom: .35em; }
#+HTML_HEAD:   .mark { font-style: normal; letter-spacing: .08em; margin-left: .3em; }
#+HTML_HEAD:   .stub { color: #888; font-style: italic; }
#+HTML_HEAD: </style>
#+HTML_HEAD: <script>window.MathJax={tex:{inlineMath:[['\\(','\\)']],displayMath:[['\\[','\\]'],['$$','$$']],tags:'ams',processEscapes:true}};</script>
#+HTML_HEAD: <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>

#+MACRO: sc @@html:<span class="smallcaps">$1</span>@@

The exercises below are mostly nontrivial extensions of the text. They
are marked by symbols with the following meaning:

- ✏ = analytic
- 💻 = computational
- 📚 = useful for the text
- 💪 = hard
- 💀 = very hard
- 🚧 = under construction

-----
* 0.1. Pauli relations @@html:<span class="mark">✏️</span>@@

Above, we presented the Pauli algebra as generated by $X, Z$ such that
\[
  X^2 = |X|^2 = Z^2 = |Z|^2 = I, \quad XZ = -ZX.
\]
Define $\sigma_1 = X$, $\sigma_3 = Z$ and $\sigma_2 = i XZ$. Verify the
/Pauli relation/
\[
  \sigma_i \sigma_j = \delta_{ij} I + i \epsilon_{ijk}\sigma_k,
\]
where $\epsilon_{123} = +1$ and is totally antisymmetric in its indices.

-----
* 0.2. The Walsh-Hadamard matrix @@html:<span class="mark">✏📚</span>@@

Recall the qudit presentation from Chapter 1.1, and define the
/Walsh-Hadamard matrix/ by
\[
  \label{eq:2}
  W = \frac{1}{\sqrt{d}}\sum_{k=0}^{d-1} X^k Z^{-(k+1)}.
\]

1. Show that $W$ is unitary. /Hint/: the geometric sum
   \[
     1 + x + \cdots + x^{d-1} = \frac{1 - x^d}{1-x}, \quad x \neq 1,
   \]
   remains valid for operators (when appropriately interpreted).
2. Prove that $W$ converts between $X$ and $Z$ in the sense that
\[
     \label{eq:4}
     W Z W^* = X, \quad W^* X W = Z.
\]
3. Finally, confirm the usual matrix elements
   \[
     W_{jk} = \langle j | W |k \rangle = \pi_0 (X^j W X^k) =
     \omega^{j(d-k)}.
   \]

-----
* 0.3. Generalized Gell-Mann matrices @@html:<span class="mark">✏💪</span>@@

We gave a presentation of the qudit algebra $\mathcal{A}_d$ in Chapter
1.1. It has the disadvantage that $X$ and $Z$ are not Hermitian (though
they are unitary). An alternative generalization of the Pauli matrices
is the /Gell-Mann matrices/, which are traceless, Hermitian, and
orthogonal in a sense we will describe below. We will define them in
terms of the unit-matrix presentation. They come in three flavours:
symmetric (S) and antisymmetric (A) matrices defined by
\[
  \lambda^\text{S}_{ab} = E_{ab} + E_{ba}, \quad \lambda^\text{A}_{ab}
  = -i(E_{ab} - E_{ba}),
\]
for $1 \leq a < b \leq d$, and diagonal (D) matrices for
$1 \leq a \leq d - 1$:
\[
  \lambda^\text{D}_{a} = -\sqrt{\frac{2}{a(a+1)}}\left[\sum_{b=1}^a
    E_{bb} - a E_{a+1,a+1}\right].
\]

1. Basic properties.
   1. Count generators and conclude that, provided we add $I$, the
      algebra has the (correct) dimension $d^2$.
   2. Verify that generators are Hermitian $\lambda = \lambda^*$,
      traceless $\mbox{tr}[\lambda]=0$, and orthogonal in the sense that
      $\mbox{tr}[\lambda\lambda'] = 0$ for $\lambda \neq \lambda'$.
   3. Show that $\mbox{tr}[\lambda^2] = 2/d$ for all $\lambda$.
2. Structure constants.
   1. Let $i, j, k$ label arbitrary Gell-Mann matrices. Confirm that the
      commutator obeys
      \[
        [\lambda_i, \lambda_j] = 2i \sum_k f_{ijk}\lambda_k, \quad
        f_{ijk} = -\frac{i}{4}\mbox{tr}[\lambda_i[\lambda_j,
        \lambda_k]].\tag{A.1}
      \]
   2. Similarly, argue that
      \[
        \{\lambda_i, \lambda_j\} = \frac{4}{d} \delta_{ij}I +
        2\sum_k d_{ijk}\lambda_k, \quad d_{ijk} =
        \frac{1}{4}\mbox{tr}[\lambda_i\{\lambda_j,
        \lambda_k\}].\tag{A.2}
      \]
   3. Check that, when $d=2$, this reproduces the Pauli relation of
      Exercise 0.1.

-----
* 1.1. Local contexts @@html:<span class="mark">💻📚</span>@@

In the ~yaw~ REPL, you evaluate expressions using the /local context/ or
/bang operator/ ~!~ (by analogy with ~#!~ which tells a UNIX shell which
interpreter to use). Some basic examples:

#+BEGIN_EXAMPLE
*> X*Z*X ! comm
X**2*Z
*> X + Z ! X = 2, Z = 3
5
#+END_EXAMPLE

These don't permanently change the variables involved, but are locally
scoped to evaluate with that assumption. In this exercise, you'll use
local context to do high school
algebra.@@html:<label for="sn-1" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-1" class="margin-toggle"/><span class="sidenote">Note that the bang operator doesn't work inside function definitions, so more generally you can use the <code>local(A, R1, R2, ...)</code> function.</span>@@

1. Consider a quadratic $p(x) = ax^2 + bx + c$. Confirm that
   \[
     p(0) = c, \quad p(1) = a + b + c, \quad p(-1) = a - b + c.
   \]
2. Write a function ~rootsFromVals(p)~ that takes a quadratic and
   produces its roots (if they exist), using local context, part (a) and
   the quadratic formula.

-----
* 1.2. Unit matrices @@html:<span class="mark">💻📚</span>@@

For the unit matrices of Chapter 1.1, the relations
\[
  E_{ab}^* = E_{ba}, \quad E_{ab}E_{cd} = \delta_{bc} E_{ad}, \quad
  \sum_a E_{aa} = I
\]
are exhaustive, as you will show below. We can implement the resulting
parameterization of $\mathcal{A}_d$ in ~yaw~ using /subscripts/ and the
generator family helper function:

#+BEGIN_EXAMPLE
*> E = GenFam('E')  # Name a generator family
*> gens = [E[(a, b)] for a in range(d)
...                  for b in range(d)]
*> rel1 = [E[(a, b)].d == E[(b, a)] for a in range(d)
...                                 for b in range(d)]
*> rel2 = [E[(a, b)]*E[(c, e)] == int(b == c)*E[(a, e)]
...        for a, b, c, e in product(range(d), repeat=4)]
*> $alg = <gens | rel1, rel2>
#+END_EXAMPLE

1. Explain why any monomial in the generators $E_{ab}$ either vanishes
   or reduces to a single term. Conclude the relations are exhaustive.
2. For $d = 2$, the Pauli matrices tell us that
   \[
     \sigma_1 = E_{12} + E_{21}, \quad \sigma_2 = i (E_{21} - E_{12}),
     \quad \sigma_3 = E_{11} - E_{22}.
   \]
   Implement the $d = 2$ presentation and check the Pauli relation of
   Exercise 0.1 for a few indices of your choice.

-----
* 1.3. Gelfand two ways @@html:<span class="mark">✏💀</span>@@

Consider the C${}^*$-algebra $\mathcal{A}_U$ generated by a single
unitary $U$. This acts on the Hilbert space of square-integrable
functions on the circle, $\mathcal{H} = L^2(\mathbb{S}^1)$, by copying
the phase:
\[
  U f(e^{i\theta}) = e^{i\theta}f(e^{i\theta}).
\]
The inner product on $\mathcal{H}$ is given by
\[
  \langle f, g\rangle = \int_{\mathbb{S}^1} \overline{f(z)} g(z)\,
  \mathrm{d}z.
\]

1. Verify directly that $U$ is a unitary operator in the sense that
   \[
     \langle U f, U g\rangle = \langle f, g\rangle.
   \]
2. The algebra as functions.
   1. Consider an arbitrary element of $\mathcal{A}_U$, namely a finite
      linear combination of powers of $U$. Argue that
      \[
        A = \sum_{k=-N}^N c_k U^k \quad \Longrightarrow \quad A
        f(e^{i\theta}) = f(e^{i\theta})\sum_{k=-N}^N c_k e^{ik\theta},
      \]
      and hence $\mathcal{A}_U$ implements multiplication by an
      arbitrary Fourier sum. Setting $f = \mathbf{1}$, show that this
      action is unique, so we can identify elements $A\in \mathcal{A}_U$
      with Fourier sums.
   2. Technically, finite linear combinations of powers of $U$ only form
      a $*$-algebra. The C${}^*$-algebra is obtained by taking the
      /closure/ (in the $L^2$ norm) of the set of finite sums. Look up
      the {{{sc(Stone-Weierstrass theorem)}}} and argue that the
      resulting closure should be $C^0(\mathbb{S}^1)$.
3. Here is another way to arrive at the same conclusion.
   1. Define the /spectrum/ $\Phi_\mathcal{A}=\text{spec}(\mathcal{A})$
      of a commutative C${}^*$-algebra $\mathcal{A}$ as the set of
      multiplicative functionals $\phi: \mathcal{A} \to \mathbb{C}$,
      also called /characters/. Argue that, for $\theta \in [0, 2\pi)$,
      the evaluation functional
      \[
        \iota_\theta (A) = A \mathbf{1} (e^{i\theta})
      \]
      is a character of $\mathcal{A}_U$.
   2. Show that a character $\phi$ on $\mathcal{A}_U$ has its value
      determined entirely by $\phi(U)$ for some $|\phi(U)|=1$. From
      this, argue that every character has the form
      $\phi = \iota_\theta$.
   3. The {{{sc(Gelfand-Naimark theorem)}}} shows that a commutative
      C${}^*$-algebra $\mathcal{A}$ may be identified with the algebra
      of continuous functions on its spectrum
      $\mathcal{A} \cong C^0(\Phi_\mathcal{A})$. Using this theorem and
      the previous parts, conclude that
      $\mathcal{A}_U \cong C^0(\mathbb{S}^1)$.

-----
* 2.1. Expectations @@html:<span class="mark">✏️</span>@@

Consider a discrete, complex-valued random variable $Z$, which takes on
values $Z = z_i \in \mathbb{C}$ with probability
$p_i = \mathbb{P}[Z = z_i]$. Then the /expectation/ of $Z$ is usually
defined as $\mathbb{E}[Z] = \sum_i p_i z_i$.

1. Properties of the expectation.
   1. Prove $\mathbb{E}[Z]$ is positive, i.e. $\mathbb{E}[Z] \geq 0$
      when all $z_i \geq 0$.
   2. Show $\mathbb{E}[Z]$ is linear, i.e.
      \[
        \mathbb{E}[\alpha Z_1 + \beta Z_2] = \alpha \mathbb{E}[Z_1] +
        \beta \mathbb{E}[Z_2].
      \]
   3. Confirm that $\mathbb{E}[Z]$ is normalized in the sense that
      $\mathbb{E}[I] = 1$, where $I$ is a random variable which always
      equals unity.
2. We will turn this round, and consider a function of random variables
   $\langle Z\rangle$ which is positive, linear and normalized. Suppose
   we can decompose $Z$ into a sum of real functions $\Pi_i^{(Z)}$
   obeying
   \[
     Z = \sum_{i} z_i \Pi_i^{(Z)}, \quad I = \sum_{i} \Pi_i^{(Z)},
     \quad \Pi_i^{(Z)} \Pi_j^{(Z)} = \delta_{ij}\Pi_i^{(Z)}.
   \]
   From this spectral decomposition, we can recover probability!
   1. Show that $q_i = \langle \Pi_i^{(Z)}\rangle$ can be interpreted as
      a probability, i.e. $q_i \geq 0$ and the $q_i$ sum to $1$.
   2. Deduce that $\langle Z\rangle = \mathbb{E}[Z]$ for the probability
      distribution $q_i$.

-----
* 2.2. GNS construction @@html:<span class="mark">💻</span>@@

The Gelfand-Naimark-Segal construction constructs a Hilbert space
$\mathcal{H}_\pi$ from a state $\pi \in S(\mathcal{A})$. We'll explore
this construction for a single qubit, starting with the eigenfunctional
$\pi = \pi^{(Z)}_0$.

1. The pseudo-Hermitian product.
   1. For $A, B \in \mathcal{A}_2$, define the pseudo-Hermitian product
      \[
        \langle A, B\rangle_{\pi}' = \pi(A^*B).
      \]
      Implement this as the function ~pseudoInner(A, B)~:

      #+BEGIN_EXAMPLE
      *> def pseudoInner(A, B):
      ...    <yourFunctionHere>
      #+END_EXAMPLE

   2. Verify (computationally) it is conjugate symmetric and additive
      \[
        \langle A, B\rangle_\pi' = \overline{\langle B, A\rangle_\pi'},
        \quad \langle A, B + C\rangle_\pi' = \langle A, B\rangle_\pi'+
        \langle A, C\rangle_\pi'
      \]
      for $A = H$, $B = Y$, and $C = Z$.
   3. Show (computationally) that the pseudo-Hermitian product is /not
      positive/, since
      \[
        \langle A, A\rangle_\pi' = 0, \quad A = Z- I.
      \]
      This means it is not a true inner product (hence the
      &ldquo;pseudo&rdquo;).
2. Reduction and the Hilbert space.
   1. To create an inner product, we can perform the following trick: we
      /identify/ $Z \sim I$, so that $Z - I \sim 0$. Define a reduction
      function $\eta_\text{red}: \mathcal{A}\to \mathcal{A}$ which
      replaces $Z$ with $I$ in an operator expression:

      #+BEGIN_EXAMPLE
      *> def reduce(A):
      ...    <yourFunctionHere>
      #+END_EXAMPLE

      /Hint:/ Check out Exercise 1.1.
   2. The Hilbert space $\mathcal{H}_\pi$ consists of all reduced
      operators $\eta_\text{red}(\mathcal{A}_2)$ with inner
      product@@html:<label for="sn-2" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-2" class="margin-toggle"/><span class="sidenote">You can show that the pseudo-Hermitian product doesn't care about \(\eta_\text{red}\): it gives the same answers for two operators with the same reduction.</span>@@
      \[
        \langle \eta_\text{red} (A), \eta_\text{red} (B)\rangle_\pi =
        \langle A,B\rangle_\pi' = \pi(A^* B).
      \]
      Check using ~yaw~ that the vectors associated to
      $I \mapsto |0\rangle$ and $X \mapsto |1\rangle$ (or simply
      $X^b \mapsto |b\rangle$) constitute an orthonormal basis for this
      space.
   3. We can view an operator $A \in \mathcal{A}$ as a matrix acting on
      $\mathcal{H}_\pi$ by $A |B\rangle_\pi = |AB\rangle_\pi$, and hence
      matrix elements
      \[
        \langle b| A |b'\rangle = \pi (X^b A X^{b'}).
      \]
      Using this recipe, numerically confirm that $H = (X + Z)/\sqrt{2}$
      has matrix representation
      \[        H \mapsto \frac{1}{\sqrt{2}}         \begin{bmatrix}           1 & 1 \\ 1 & -1         \end{bmatrix}.
      \]

-----
* 2.3. The noncommutative torus @@html:<span class="mark">✏💀</span>@@

Recall that a single unitary $U$ generates functions on the circle
$\mathbb{S}^1$ (Exercise 1.3). We will explore the different
spaces---and states---generated by two unitaries $U$ and $V$.

1. Consider the algebra $\mathcal{A}_{U,V}$ of commuting unitaries,
   $UV = VU$. It acts on the Hilbert space of square-integrable
   functions $\mathcal{H} = L^2(\mathbb{S}^1\times \mathbb{S}^1)$ via
   \[
     U f(e^{i\alpha}, e^{i\beta}) = e^{i\alpha} f(e^{i\alpha},
     e^{i\beta}), \quad V f(e^{i\alpha}, e^{i\beta}) = e^{i\beta}
     f(e^{i\alpha}, e^{i\beta}).
   \]
   1. Verify that $U$ and $V$ are unitary and commute.
   2. By an argument (or two!) analogous to Exercise 1.3, show that
      $\mathcal{A}_{U,V} \cong C^0(\mathbb{T}^2)$, where
      $\mathbb{T}^2 = \mathbb{S}^1\times \mathbb{S}^1$ is the
      /torus/.@@html:<label for="sn-3" class="margin-toggle sidenote-number"></label><input type="checkbox" id="sn-3" class="margin-toggle"/><span class="sidenote">Also known as the donut.</span>@@
   3. For a square-integrable Fourier series
      \[
        A = \sum_{m,n\in\mathbb{Z}} c_{m,n} U^m V^n,
      \]
      argue that the coefficient projection $\pi_{0}(A) = c_{0,0}$ is a
      state, i.e. linear, normalized, and positive.
   4. Show that no other coefficients $c_{m,n}$ are states.
2. Now consider the algebra $\mathcal{A}_\theta$ with two unitary
   generators $U$ and $V$ satisfying a braiding relation
   $VU = e^{i\theta} UV$ for $\theta \not\in 2\pi\mathbb{Z}$. For
   square-integrable functions on $\mathbb{S}^1$, define
   \[
     Uf (e^{i\alpha}) = e^{i\alpha} f(e^{i\alpha}), \quad V
     f(e^{i\alpha}) = f(e^{i\alpha-\theta}).
   \]
   This algebra is called the /noncommutative torus/.
   1. Verify that $U$ and $V$ are unitary and braid appropriately.
   2. Argue that, for the Fourier series
      \[
        A = \sum_{m,n\in\mathbb{Z}} c_{m,n} U^m V^n,
      \]
      the coefficient projection $\pi_{0}(A) = c_{0,0}$ is a state.
   3. If $\theta$ is irrational, argue that no other coefficient
      projection is a state. Conversely, if $\theta \in \mathbb{Q}$ is
      rational, argue that $c_{m,n}$ is a state whenever
      $\theta m, \theta n \in \mathbb{Z}$.

-----
* 3.1. Hadamard? @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 3.2. EPR @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@Factorization, qudit version. To be
written.@@html:</span>@@

-----
* 3.3. Qudit depolarizer @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 3.4. Many worlds (branching) @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 4.1. Single-qudit unitaries @@html:<span class="mark">🚧✏️</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 4.2. Variance and averages @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 4.3. Operator mirroring @@html:<span class="mark">🚧✏️</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 4.4. Gate teleportation @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 4.5. Causality and encryption @@html:<span class="mark">🚧✏</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 5.1. A Hamiltonian @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 5.2. Rabi uncertainty @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 5.3. Trotter-Suzuki @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 5.4. Multiple marked items @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 5.5. Rotation geometry @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 6.1. Check algorithm @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 6.2. QFT parallelization in qudits @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* 6.3. Normal subgroups @@html:<span class="mark">🚧💻</span>@@

@@html:<span class="stub">@@To be written.@@html:</span>@@

-----
* COMMENT html export
#+TITLE:
#+HTML_CONTAINER: div
#+HTML_DOCTYPE: xhtml-strict
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="enhanced_tufte.css">
#+HTML_HEAD: <script src="contents.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="sidebar_darkmode.js"></script>
#+HTML_HEAD: <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
#+HTML_LINK_UP:
#+HTML_MATHJAX: 
#+INFOJS_OPT:
#+LATEX_HEADER:
#+OPTIONS: html-postamble:nil toc:nil 
#+HTML_HEAD_EXTRA: <style>pre { padding-top: 25px !important; }</style>
